apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wxtu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wxtu
    app.kubernetes.io/part-of: ci10t-776-0035-app
  name: devfile-sample-wxtu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wxtu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wxtu
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0035-tenant/ci10t-776-0035-app/devfile-sample-wxtu@sha256:e991d59b97fb4cf1136da85116db1f050cb008586a54993e70db6a12a239c591
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
