apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wxtu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0035-tenant/ci10t-776-0035-app/devfile-sample-wxtu@sha256:e991d59b97fb4cf1136da85116db1f050cb008586a54993e70db6a12a239c591
        name: my-nodejs
        resources: {}
status: {}
